### ISSUE TITLE
Level #1 - Constant Board

### ISSUE THREAD

**Issue by ShalomPrinz** [ShalomPrinz/Pacman#1]
The game will show the initial game board, which contains: Pacman , four ghosts , walls and points to eat.

**Comment by danprinz** [comment]
What are the dimensions of the board?
How many point to eat should be placed?

**Comment by danprinz** [comment]
Also, I think that a ghost might be placed where a point is, because they move around. 
Otherwise what should be happen when a ghost moves to a point place?

**Comment by ShalomPrinz** [comment]
Board dimensions: 30x30
On ghosts base and on the near square to it, there won't be points.
Except from this, wherever there is no wall - there will be a point.
When a ghost moves to a point place, noting happens. The ghost just move over the point.
