### ISSUE TITLE
Level #2 - Moving Board

### ISSUE THREAD

**Issue by ShalomPrinz** [ShalomPrinz/Pacman#2]
There will be four buttons - right, left, up, down. On a button click the Pacman will move one step, to the button direction. The ghosts will also move one step, to a random direction.

**Comment by danprinz** [comment]
I think it would be nice to attach some wireframes to make it clear how and where the buttons should be placed

**Comment by ShalomPrinz** [comment]
I agree, but I didn't insert any graphics details.. should I do so?

**Comment by ShalomPrinz** [comment]
Level #2.1 - Timer & Moving, detailed
The game will hold a direction (enum value). default direction - left.
The game will activate a timer, and the timer will move the board every 200 milliseconds. 
Timer moving: the pacman will move according to the direction. 
ghosts will move to a random direction until they can't keep moving, and then they will change direction.

* Clicking on a button will change the (pacman) direction. But if the pacman can't move to the desireable direction, pacman will keep moving on the previous direction until he can move to the new direction.
