### ISSUE TITLE
Level #4 - Ghosts

### ISSUE THREAD

**Issue by ShalomPrinz** [ShalomPrinz/Pacman#4]
If one of the ghosts will go on the Pacman, the game will stop and start over. On the third time, the player has lost the game - it will stop, and the score will be added to the high score list.

**Comment by danprinz** [comment]
What do you mean by “start over“? Will the board reset to its default status or should it continue from the same game/board state?
And what about the score? Should it be reset to 0 or continue?

**Comment by ShalomPrinz** [comment]
I will rephrase it.
If one of the ghosts will go on the Pacman, the game will stop. The Pacman and the ghosts will go back to their start point. The rest of the board will remain the same, all the walls and points will stay the same.
Also, the score won't be affected. 
On the Pacman third death, the game will stop, and the game score will be added to the high score list.
