### ISSUE TITLE
Level #5 - Ghosts Eating

### ISSUE THREAD

**Issue by ShalomPrinz** [ShalomPrinz/Pacman#5]
Big points will be added to the game board. When the Pacman eats them, all the ghosts will become scary blue ghosts, and much slower. Now the Pacman will have a window of opportunity, for 10 seconds, to eat the ghosts. If the Pacman eats a ghost, it will move regularly, and it will have only eyes - for 10 seconds. For every ghost eat, 200 points will be added to the game score. (First ghost 200, then 400, 800, 1600)

**Comment by danprinz** [comment]
I think it’s better to split this issue to several sub-tasks. 
e.g. maybe eating a ghost should be 1 task and in other task the “scary eyes” will be treated. 
Also, it would be better to have constant score given for every ghost, instead of multiplying it by 2 (at least for this phase).

**Comment by danprinz** [comment]
How many “big points” should be added?
Where it will be placed? Randomly?

**Comment by ShalomPrinz** [comment]
Level #5, splitted into sub-tasks.

5.1 - 4 Big points will be added to the 4 board's corners. If the Pacman eats a big point, he can eat the ghosts for 10 seconds.

5.2 - On those 10 seconds, all the ghosts will become scary blue ghosts, and much slower. 

5.3 - If the Pacman eats a ghost, the eaten ghost will move regularly, and it will have only eyes - for 10 seconds.

5.4 - For every ghost eat, 200 points will be added to the game score.
